alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
databases:
- cluster_name: mongodb1
  engine: MONGODB
  name: mongodb1
  production: true
  version: "8"
domains:
- domain: monkeyz.co.il
  type: PRIMARY
  zone: monkeyz.co.il
- domain: www.monkeyz.co.il
  type: ALIAS
  zone: monkeyz.co.il
envs:
- key: REACT_APP_PATH_BACKEND
  scope: RUN_AND_BUILD_TIME
  value: |
    https://api.monkeyz.co.il
- key: REACT_APP_GOOGLE_CLIENT_ID
  scope: RUN_AND_BUILD_TIME
  value: 946645411512-tn9qmppcsnp5oqqo88ivkuapou2cmg53.apps.googleusercontent.com
- key: REACT_APP_PAYMENT_FAIL_URL
  scope: RUN_AND_BUILD_TIME
  value: https://monkeyz.co.il/fail
- key: REACT_APP_PAYMENT_SUCCESS_URL
  scope: RUN_AND_BUILD_TIME
  value: https://monkeyz.co.il/success
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: front-end
    match:
      path: /
name: monkeyz
region: fra
services:
- build_command: npm ci && npm run build
  environment_slug: static-site
  github:
    branch: main
    deploy_on_push: true
    repo: YOURUSERNAME/YOURREPO
  name: front-end
  source_dir: frontend/
  output_dir: build
  routes:
  - path: /
  envs:
  - key: REACT_APP_PATH_BACKEND
    scope: BUILD_TIME
    value: \
  - key: REACT_APP_GOOGLE_CLIENT_ID
    scope: BUILD_TIME
    value: \
    type: SECRET
  - key: REACT_APP_PAYMENT_FAIL_URL
    scope: BUILD_TIME
    value: \/fail
  - key: REACT_APP_PAYMENT_SUCCESS_URL
    scope: BUILD_TIME
    value: \/success
