alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILEDstatic_sites:
- build_command: npm ci --prefer-offline --no-audit --silent && npm run build
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: EvyaIL/MonkeyZ
  name: front-end
  source_dir: frontend/
  output_dir: build/
  index_document: index.html
  error_document: index.html
  routes:
  - path: /- cluster_name: mongodb1
  engine: MONGODB
  name: mongodb1
  production: true
  version: "8"
domains:
- domain: monkeyz.co.il
  type: PRIMARY
  zone: monkeyz.co.il
- domain: www.monkeyz.co.il
  type: ALIAS
  zone: monkeyz.co.il
envs:
- key: REACT_APP_PATH_BACKEND
  scope: RUN_AND_BUILD_TIME
  value: https://api.monkeyz.co.il
- key: REACT_APP_GOOGLE_CLIENT_ID
  scope: RUN_AND_BUILD_TIME
  value: 946645411512-tn9qmppcsnp5oqqo88ivkuapou2cmg53.apps.googleusercontent.com
- key: REACT_APP_PAYMENT_FAIL_URL
  scope: RUN_AND_BUILD_TIME
  value: https://monkeyz.co.il/fail
- key: REACT_APP_PAYMENT_SUCCESS_URL
  scope: RUN_AND_BUILD_TIME
  value: https://monkeyz.co.il/success
- key: REACT_APP_GA_MEASUREMENT_ID
  scope: RUN_AND_BUILD_TIME
  value: G-SYF721LFGB
- key: REACT_APP_GTM_ID
  scope: RUN_AND_BUILD_TIME
  value: GTM-P4FNQL6X
- key: REACT_APP_API_URL
  scope: RUN_AND_BUILD_TIME
  value: https://api.monkeyz.co.il
- key: REACT_APP_PAYMENT_CANCEL_URL
  scope: RUN_AND_BUILD_TIME
  value: https://monkeyz.co.il/checkout
- key: REACT_APP_PAYPAL_SUCCESS_URL
  scope: RUN_AND_BUILD_TIME
  value: https://monkeyz.co.il/success
- key: REACT_APP_PAYPAL_CLIENT_ID
  scope: RUN_AND_BUILD_TIME
  value: AXu-4q2i_746jXHFnUbYUSDxSHZF5og7QtErtmy9eJHkzBpumtDFLpJz6OQollNpRDFlqP2w3rg7DiCF
- key: NODE_OPTIONS
  scope: BUILD_TIME
  value: --max-old-space-size=2048
- key: GENERATE_SOURCEMAP
  scope: BUILD_TIME
  value: "false"
- key: DISABLE_ESLINT_PLUGIN
  scope: BUILD_TIME
  value: "true"
- key: TSC_COMPILE_ON_ERROR
  scope: BUILD_TIME
  value: "true"
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: front-end
    match:
      path: /
name: monkeyz
region: fra
static_sites:
- build_command: npm ci --silent && npm run build
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: EvyaIL/MonkeyZ
  name: front-end
  source_dir: frontend/
  output_dir: build/
  index_document: index.html
  error_document: index.html
  routes:
  - path: /
