name: monkeyz-app
services:
- environment_slug: static-site
  github:
    branch: main
    deploy_on_push: true
    repo: EvyaIL/CDMonkey
  name: cdmonkey-frontend
  build_command: cd frontend; npm install; npm run build
  source_dir: frontend
  output_dir: build
  routes:
  - path: /