name: monkeyz-backend
services:
- name: api
  github:
    branch: main
    deploy_on_push: true
    repo: EvyaIL/MonkeyZ
  source_dir: .
  http_port: 8000
  instance_count: 1
  instance_size_slug: basic-xs
  routes:
  - path: /
  envs:
  - key: MONGODB_URI
    scope: RUN_TIME
    value: 
    type: SECRET
  - key: SECRET_KEY
    scope: RUN_TIME
    value: 
    type: SECRET
  - key: ALGORITHM
    scope: RUN_TIME
    value: HS256
  - key: ACCESS_TOKEN_EXPIRE_MINUTES
    scope: RUN_TIME
    value: "30"
  - key: ALLOWED_ORIGINS
    scope: RUN_TIME
    value: "http://localhost:3000,https://monkeyz.co.il,https://www.monkeyz.co.il,https://monkeyz-frontend.ondigitalocean.app"
  health_check:
    http_path: /health
    initial_delay_seconds: 30
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
    period_seconds: 10
